use_frameworks!

platform :ios, '8.0'

target 'PodLibDemo_Example' do
  pod 'PodLibDemo', :path => '../'

  target 'PodLibDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
